# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# Use the same key to share cached across branchs and jobs
image: node:16.13

cache:
  key: one-key-to-rule-them-all
  paths:
  - node_modules/
  - .yarn

before_script:
  - yarn install --cache-folder .yarn

stages:
  - build
  - test

build:
  stage: build
  variables:
    FILE_SERVER_IP: "$FILE_SERVER_IP"
    FILE_SERVER_PRIVATE_SSH_KEY: "$FILE_SERVER_PRIVATE_SSH_KEY"
    FILE_SERVER_BUILD_DIR: "$FILE_SERVER_BUILD_DIR"
  script:
    - apt-get update && apt-get install -y zip unzip
    - mkdir -p ~/.ssh
    - echo "$FILE_SERVER_PRIVATE_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $FILE_SERVER_IP >> ~/.ssh/known_hosts
    - yarn --version

    - CI=false yarn build
    - zip build.zip -r build/
    - ls -lh build.zip
    - scp build.zip root@$FILE_SERVER_IP:$FILE_SERVER_BUILD_DIR
    - SUCCESS_MSG="$(TZ=Asia/Ho_Chi_Minh date +'%F %T %Z') - Build Success, commit $(git rev-parse HEAD)"
    - ssh root@$FILE_SERVER_IP "echo $SUCCESS_MSG >> $FILE_SERVER_BUILD_DIR/build.log"

  only:
    - master

