const Types = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  CLEAR_USER: 'CLEAR_USER',
  LOGIN: 'LOGIN',
  SPLASH: 'SPLASH',
  LAYOUT_ORDER_BOOK: 'LAYOUT_ORDER_BOOK',
  LIST_ORDER: 'LIST_ORDER',
  SECRET_KEY: 'SECRET_KEY',
  REMEMBER_KEY: 'REMEMBER_KEY',
  TAB_BLOCK: 'TAB_BLOCK',
  WARNING_MESSAGE: 'WARNING_MESSAGE'
};

export default Types;
