const Types = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  CLEAR_USER: 'CLEAR_USER',
  LOGIN: 'LOGIN',
  SPLASH: 'SPLASH',
  LAYOUT_ORDER_BOOK: 'LAYOUT_ORDER_BOOK',
  LIST_ORDER_MULTI_ORDER: 'LIST_ORDER_MULTI_ORDER'

};

export default Types;
